apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.deployment.name}}
 namespace: {{.Values.namespace.name}}
spec:
 replicas: {{.Values.deployment.replicas}}
 selector:
  matchLabels:
   app: {{.Values.deployment.label}}
 template:
  metadata:
   labels:
    app: {{.Values.deployment.label}}
  spec:
   containers:
    - name: {{.Values.deployment.label}}
      image: {{.Values.deployment.repository }}:{{ .Values.deployment.version }}
      imagePullPolicy: {{.Values.deployment.pullPolicy}}
      livenessProbe:
       httpGet:
        path: {{.Values.deployment.livenessProbe.path}}
        port: {{.Values.deployment.livenessProbe.port}}
      readinessProbe:
       httpGet:
        path: {{.Values.deployment.readinessProbe.path}}
        port: {{.Values.deployment.readinessProbe.port}}
      resources:
       requests:
        memory: {{.Values.deployment.resources.requests.memory}}
        cpu: {{.Values.deployment.resources.requests.cpu}}
       limits:
        memory: {{.Values.deployment.resources.limits.memory}}
        cpu: {{.Values.deployment.resources.limits.cpu}}
      ports:
      - containerPort: {{.Values.deployment.containerPort}}