name: Production
on:
  push:
   branches:
     - master

jobs:
  build:
   runs-on: ubuntu-latest
   timeout-minutes: 10
   steps:
    - uses: actions/checkout@v2
    - name: Login with Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME}}
       password: ${{ secrets.DOCKERHUB_TOKEN}}
    - name: Build Docker Image
      run: docker build -t gitops:${{ github.sha }} .
      working-directory: src/GitOps
    - name: Tag Docker Image
      run: docker tag gitops:${{ github.sha }} mmsaad85/gitops:${{ github.sha }}
      working-directory: src/GitOps
    - name: Push Docker Image
      run: docker push mmsaad85/gitops:${{ github.sha }}
      working-directory: src/GitOps